services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"

  fmsevalueringui:
    image: ${DOCKER_REGISTRY-}fmsevalueringui
    build:
      context: .
      dockerfile: FMSEvalueringUI/Dockerfile

  fmsevaluering.api:
    image: ${DOCKER_REGISTRY-}fmsevalueringapi
    build:
      context: .
      dockerfile: FMSEvaluering.Api/Dockerfile

  gateway.api:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: GatewayAPI/Gateway.API/Dockerfile

  fmsdataserver.api:
    image: ${DOCKER_REGISTRY-}fmsdataserverapi
    build:
      context: .
      dockerfile: FMSDataServer.Api/Dockerfile

  fmsexitslip.api:
    image: ${DOCKER_REGISTRY-}fmsexitslipapi
    build:
      context: .
      dockerfile: FMSExitSlip.Api/Dockerfile

